// Generated by https://quicktype.io

export interface UserResponse {
  data: UserData;
  support: Support;
}

export interface UserData {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  avatar: string;
}

interface Support {
  url: string;
  text: string;
}
